name: Deploy SQL to PostgreSQL

on:
  push:
    paths:
      - 'db/migrations/*.sql'

jobs:
  deploy-sql:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy SQL to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "db/migrations/*.sql"
          target: "/home/ubuntu/sql-deploy"

      - name: Execute SQL in PostgreSQL
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            export PGPASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            for file in /home/ubuntu/sql-deploy/db/migrations/*.sql
            do
              psql -h localhost -U postgres -d arc_db -v ON_ERROR_STOP=1 -f "$file"
            done